// medicationAlternatives.js
const medicationAlternatives = {
    'Aspirin': ['Ibuprofen', 'Naproxen', 'Paracetamol'],
    'Ibuprofen': ['Aspirin', 'Naproxen', 'Paracetamol'],
    'Paracetamol': ['Ibuprofen', 'Naproxen', 'Aspirin'],
    'Amoxicillin': ['Azithromycin', 'Clindamycin', 'Cefalexin'],
    'Metformin': ['Glibenclamide', 'Gliclazide', 'Pioglitazone'],
    'Lisinopril': ['Losartan', 'Amlodipine', 'Captopril'],
    'Simvastatin': ['Atorvastatin', 'Rosuvastatin', 'Pravastatin'],
    'Amoxicillin': ['Azithromycin', 'Cefalexin', 'Clindamycin'],
    'Fluoxetine': ['Sertraline', 'Citalopram', 'Escitalopram'],
    'Sertraline': ['Fluoxetine', 'Citalopram', 'Escitalopram'],
    'Citalopram': ['Fluoxetine', 'Sertraline', 'Escitalopram'],
    'Nitroglycerin': ['Isosorbide mononitrate', 'Amlodipine', 'Diltiazem'],
    'Losartan': ['Valsartan', 'Irbesartan', 'Candesartan'],
    'Metoprolol': ['Atenolol', 'Propranolol', 'Carvedilol'],
    'Atorvastatin': ['Simvastatin', 'Rosuvastatin', 'Lovastatin'],
    'Rosuvastatin': ['Atorvastatin', 'Simvastatin', 'Pravastatin'],
    'Levothyroxine': ['Liothyronine', 'Thyroid extract', 'Desiccated thyroid'],
    'Omeprazole': ['Esomeprazole', 'Lansoprazole', 'Pantoprazole'],
    'Esomeprazole': ['Omeprazole', 'Lansoprazole', 'Pantoprazole'],
    'Lansoprazole': ['Omeprazole', 'Esomeprazole', 'Pantoprazole'],
    'Pantoprazole': ['Omeprazole', 'Esomeprazole', 'Lansoprazole'],
    'Amlodipine': ['Felodipine', 'Nifedipine', 'Diltiazem'],
    'Diltiazem': ['Amlodipine', 'Verapamil', 'Nifedipine'],
    'Verapamil': ['Diltiazem', 'Amlodipine', 'Nifedipine'],
    'Nifedipine': ['Amlodipine', 'Felodipine', 'Diltiazem'],
    'Hydrochlorothiazide': ['Chlorthalidone', 'Indapamide', 'Metolazone'],
    'Furosemide': ['Bumetanide', 'Torsemide', 'Ethacrynic acid'],
    'Bumetanide': ['Furosemide', 'Torsemide', 'Ethacrynic acid'],
    'Torsemide': ['Furosemide', 'Bumetanide', 'Ethacrynic acid'],
    'Levocetirizine': ['Cetirizine', 'Desloratadine', 'Fexofenadine'],
    'Cetirizine': ['Levocetirizine', 'Desloratadine', 'Fexofenadine'],
    'Desloratadine': ['Levocetirizine', 'Cetirizine', 'Fexofenadine'],
    'Fexofenadine': ['Levocetirizine', 'Cetirizine', 'Desloratadine'],
    'Loratadine': ['Cetirizine', 'Fexofenadine', 'Desloratadine'],
    'Dexamethasone': ['Prednisone', 'Hydrocortisone', 'Methylprednisolone'],
    'Prednisone': ['Dexamethasone', 'Hydrocortisone', 'Methylprednisolone'],
    'Hydrocortisone': ['Dexamethasone', 'Prednisone', 'Methylprednisolone'],
    'Methylprednisolone': ['Dexamethasone', 'Prednisone', 'Hydrocortisone'],
    'Montelukast': ['Zafirlukast', 'Buspirone', 'Theophylline'],
    'Zafirlukast': ['Montelukast', 'Buspirone', 'Theophylline'],
    'Ranitidine': ['Famotidine', 'Nizatidine', 'Cimetidine'],
    'Famotidine': ['Ranitidine', 'Nizatidine', 'Cimetidine'],
    'Nizatidine': ['Ranitidine', 'Famotidine', 'Cimetidine'],
    'Cimetidine': ['Ranitidine', 'Famotidine', 'Nizatidine'],
    'Sildenafil': ['Tadalafil', 'Vardenafil', 'Avanafil'],
    'Tadalafil': ['Sildenafil', 'Vardenafil', 'Avanafil'],
    'Vardenafil': ['Sildenafil', 'Tadalafil', 'Avanafil'],
    'Avanafil': ['Sildenafil', 'Tadalafil', 'Vardenafil'],
    'Carbamazepine': ['Lamotrigine', 'Phenytoin', 'Valproate'],
    'Lamotrigine': ['Carbamazepine', 'Phenytoin', 'Valproate'],
    'Phenytoin': ['Carbamazepine', 'Lamotrigine', 'Valproate'],
    'Valproate': ['Carbamazepine', 'Lamotrigine', 'Phenytoin'],
    'Ciprofloxacin': ['Levofloxacin', 'Ofloxacin', 'Moxifloxacin'],
    'Levofloxacin': ['Ciprofloxacin', 'Ofloxacin', 'Moxifloxacin'],
    'Ofloxacin': ['Ciprofloxacin', 'Levofloxacin', 'Moxifloxacin'],
    'Moxifloxacin': ['Ciprofloxacin', 'Levofloxacin', 'Ofloxacin'],
    'Clindamycin': ['Vancomycin', 'Doxycycline', 'Metronidazole'],
    'Doxycycline': ['Minocycline', 'Tetracycline', 'Clindamycin'],
    'Minocycline': ['Doxycycline', 'Tetracycline', 'Clindamycin'],
    'Tetracycline': ['Doxycycline', 'Minocycline', 'Clindamycin'],
    'Nitrofurantoin': ['Trimethoprim-sulfamethoxazole', 'Ciprofloxacin', 'Amoxicillin'],
    'Trimethoprim-sulfamethoxazole': ['Nitrofurantoin', 'Ciprofloxacin', 'Amoxicillin'],
    'Phenylephrine': ['Pseudoephedrine', 'Oxymetazoline', 'Afrin'],
    'Pseudoephedrine': ['Phenylephrine', 'Oxymetazoline', 'Afrin'],
    'Oxymetazoline': ['Phenylephrine', 'Pseudoephedrine', 'Afrin'],
    'Afrin': ['Phenylephrine', 'Pseudoephedrine', 'Oxymetazoline'],
    'Benzonatate': ['Dextromethorphan', 'Codeine', 'Hydrocodone'],
    'Dextromethorphan': ['Benzonatate', 'Codeine', 'Hydrocodone'],
    'Codeine': ['Dextromethorphan', 'Benzonatate', 'Hydrocodone'],
    'Hydrocodone': ['Dextromethorphan', 'Benzonatate', 'Codeine'],
    'Diphenhydramine': ['Chlorpheniramine', 'Loratadine', 'Cetirizine'],
    'Chlorpheniramine': ['Diphenhydramine', 'Loratadine', 'Cetirizine'],
    'Ketorolac': ['Ibuprofen', 'Naproxen', 'Diclofenac'],
    'Diclofenac': ['Ibuprofen', 'Naproxen', 'Ketorolac'],
    'Piroxicam': ['Naproxen', 'Diclofenac', 'Ibuprofen'],
    'Naproxen': ['Ibuprofen', 'Diclofenac', 'Ketorolac'],
    'Loperamide': ['Diphenoxylate', 'Bismuth subsalicylate', 'Psyllium'],
    'Diphenoxylate': ['Loperamide', 'Bismuth subsalicylate', 'Psyllium'],
    'Bismuth subsalicylate': ['Loperamide', 'Diphenoxylate', 'Psyllium'],
    'Amitriptyline': ['Nortriptyline', 'Doxepin', 'Desipramine'],
    'Nortriptyline': ['Amitriptyline', 'Doxepin', 'Desipramine'],
    'Doxepin': ['Amitriptyline', 'Nortriptyline', 'Desipramine'],
    'Desipramine': ['Amitriptyline', 'Nortriptyline', 'Doxepin'],
    'Quetiapine': ['Risperidone', 'Olanzapine', 'Aripiprazole'],
    'Risperidone': ['Quetiapine', 'Olanzapine', 'Aripiprazole'],
    'Olanzapine': ['Quetiapine', 'Risperidone', 'Aripiprazole'],
    'Aripiprazole': ['Quetiapine', 'Risperidone', 'Olanzapine'],
    'Bupropion': ['Venlafaxine', 'Duloxetine', 'Desvenlafaxine'],
    'Venlafaxine': ['Bupropion', 'Duloxetine', 'Desvenlafaxine'],
    'Duloxetine': ['Bupropion', 'Venlafaxine', 'Desvenlafaxine'],
    'Desvenlafaxine': ['Bupropion', 'Venlafaxine', 'Duloxetine'],
    'Dexamethasone': ['Prednisone', 'Hydrocortisone', 'Methylprednisolone'],
    'Prednisone': ['Dexamethasone', 'Hydrocortisone', 'Methylprednisolone'],
    'Hydrocortisone': ['Dexamethasone', 'Prednisone', 'Methylprednisolone'],
    'Methylprednisolone': ['Dexamethasone', 'Prednisone', 'Hydrocortisone'],
    'Fluticasone': ['Budesonide', 'Mometasone', 'Beclomethasone'],
    'Budesonide': ['Fluticasone', 'Mometasone', 'Beclomethasone'],
    'Mometasone': ['Fluticasone', 'Budesonide', 'Beclomethasone'],
    'Beclomethasone': ['Fluticasone', 'Budesonide', 'Mometasone'],
    'Theophylline': ['Aminophylline', 'Ipratropium', 'Montelukast'],
    'Aminophylline': ['Theophylline', 'Ipratropium', 'Montelukast'],
    'Ipratropium': ['Theophylline', 'Aminophylline', 'Montelukast'],
    'Methotrexate': ['Leucovorin', 'Azathioprine', 'Cyclophosphamide'],
    'Azathioprine': ['Methotrexate', 'Leucovorin', 'Cyclophosphamide'],
    'Cyclophosphamide': ['Methotrexate', 'Azathioprine', 'Leucovorin'],
    'Simethicone': ['Lactase', 'Beano', 'Activated charcoal'],
    'Lactase': ['Simethicone', 'Beano', 'Activated charcoal'],
    'Beano': ['Simethicone', 'Lactase', 'Activated charcoal'],
    'Activated charcoal': ['Simethicone', 'Lactase', 'Beano'],
    'Albuterol': ['Levalbuterol', 'Terbutaline', 'Ipratropium'],
    'Levalbuterol': ['Albuterol', 'Terbutaline', 'Ipratropium'],
    'Terbutaline': ['Albuterol', 'Levalbuterol', 'Ipratropium'],
    'Ipratropium': ['Albuterol', 'Levalbuterol', 'Terbutaline'],
    'Acetazolamide': ['Methazolamide', 'Bicarbonate', 'Hydrochlorothiazide'],
    'Methazolamide': ['Acetazolamide', 'Bicarbonate', 'Hydrochlorothiazide'],
    'Bicarbonate': ['Acetazolamide', 'Methazolamide', 'Hydrochlorothiazide'],
    'Atenolol': ['Metoprolol', 'Bisoprolol', 'Carvedilol'],
    'Bisoprolol': ['Atenolol', 'Metoprolol', 'Carvedilol'],
    'Propranolol': ['Metoprolol', 'Atenolol', 'Bisoprolol'],
    'Rocuronium': ['Vecuronium', 'Atracurium', 'Cisatracurium'],
    'Vecuronium': ['Rocuronium', 'Atracurium', 'Cisatracurium'],
    'Atracurium': ['Rocuronium', 'Vecuronium', 'Cisatracurium'],
    'Cisatracurium': ['Rocuronium', 'Vecuronium', 'Atracurium'],
    'Enalapril': ['Ramipril', 'Lisinopril', 'Quinapril'],
    'Ramipril': ['Enalapril', 'Lisinopril', 'Quinapril'],
    'Quinapril': ['Enalapril', 'Ramipril', 'Lisinopril'],
    'Finasteride': ['Dutasteride', 'Tamsulosin', 'Alfuzosin'],
    'Dutasteride': ['Finasteride', 'Tamsulosin', 'Alfuzosin'],
    'Tamsulosin': ['Finasteride', 'Dutasteride', 'Alfuzosin'],
    'Alfuzosin': ['Finasteride', 'Dutasteride', 'Tamsulosin'],
    'Rivaroxaban': ['Apixaban', 'Edoxaban', 'Dabigatran'],
    'Apixaban': ['Rivaroxaban', 'Edoxaban', 'Dabigatran'],
    'Edoxaban': ['Rivaroxaban', 'Apixaban', 'Dabigatran'],
    'Dabigatran': ['Rivaroxaban', 'Apixaban', 'Edoxaban'],
    'Bivalirudin': ['Argatroban', 'Desirudin', 'Fondaparinux'],
    'Argatroban': ['Bivalirudin', 'Desirudin', 'Fondaparinux'],
    'Desirudin': ['Bivalirudin', 'Argatroban', 'Fondaparinux'],
    'Fondaparinux': ['Bivalirudin', 'Argatroban', 'Desirudin'],
    'Varenicline': ['Bupropion', 'Nicotine patch', 'Nicotine gum'],
    'Bupropion': ['Varenicline', 'Nicotine patch', 'Nicotine gum'],
    'Nicotine patch': ['Varenicline', 'Bupropion', 'Nicotine gum'],
    'Nicotine gum': ['Varenicline', 'Bupropion', 'Nicotine patch'],
    'Gabapentin': ['Pregabalin', 'Carbamazepine', 'Lamotrigine'],
    'Pregabalin': ['Gabapentin', 'Carbamazepine', 'Lamotrigine'],
    'Lansoprazole': ['Omeprazole', 'Esomeprazole', 'Pantoprazole'],
    'Clonazepam': ['Lorazepam', 'Alprazolam', 'Diazepam'],
    'Lorazepam': ['Clonazepam', 'Alprazolam', 'Diazepam'],
    'Alprazolam': ['Clonazepam', 'Lorazepam', 'Diazepam'],
    'Diazepam': ['Clonazepam', 'Lorazepam', 'Alprazolam'],
    'Clarithromycin': ['Azithromycin', 'Erythromycin', 'Doxycycline'],
    'Azithromycin': ['Clarithromycin', 'Erythromycin', 'Doxycycline'],
    'Erythromycin': ['Clarithromycin', 'Azithromycin', 'Doxycycline'],
    'Dabigatran': ['Rivaroxaban', 'Apixaban', 'Edoxaban'],
    'Cholecalciferol': ['Ergocalciferol', 'Calcitriol', 'Calcium carbonate'],
    'Ergocalciferol': ['Cholecalciferol', 'Calcitriol', 'Calcium carbonate'],
    'Calcitriol': ['Cholecalciferol', 'Ergocalciferol', 'Calcium carbonate'],
    'Calcium carbonate': ['Cholecalciferol', 'Ergocalciferol', 'Calcitriol'],
    'Levocarnitine': ['Carnitine', 'Propionylcarnitine', 'L-carnitine'],
    'Carnitine': ['Levocarnitine', 'Propionylcarnitine', 'L-carnitine'],
    'Propionylcarnitine': ['Levocarnitine', 'Carnitine', 'L-carnitine'],
    'L-carnitine': ['Levocarnitine', 'Carnitine', 'Propionylcarnitine'],
    'Zolpidem': ['Eszopiclone', 'Temazepam', 'Triazolam'],
    'Eszopiclone': ['Zolpidem', 'Temazepam', 'Triazolam'],
    'Temazepam': ['Zolpidem', 'Eszopiclone', 'Triazolam'],
    'Triazolam': ['Zolpidem', 'Eszopiclone', 'Temazepam'],
    'Olmesartan': ['Losartan', 'Irbesartan', 'Valsartan'],
    'Irbesartan': ['Losartan', 'Olmesartan', 'Valsartan'],
    'Valsartan': ['Losartan', 'Olmesartan', 'Irbesartan'],
    'Labetalol': ['Carvedilol', 'Atenolol', 'Bisoprolol'],
    'Carvedilol': ['Labetalol', 'Atenolol', 'Bisoprolol'],
    'Ritonavir': ['Lopinavir', 'Nelfinavir', 'Saquinavir'],
    'Lopinavir': ['Ritonavir', 'Nelfinavir', 'Saquinavir'],
    'Nelfinavir': ['Ritonavir', 'Lopinavir', 'Saquinavir'],
    'Saquinavir': ['Ritonavir', 'Lopinavir', 'Nelfinavir'],
    'Voriconazole': ['Fluconazole', 'Itraconazole', 'Ketoconazole'],
    'Fluconazole': ['Voriconazole', 'Itraconazole', 'Ketoconazole'],
    'Itraconazole': ['Voriconazole', 'Fluconazole', 'Ketoconazole'],
    'Ketoconazole': ['Voriconazole', 'Fluconazole', 'Itraconazole'],
    'Acyclovir': ['Valacyclovir', 'Famciclovir', 'Penciclovir'],
    'Valacyclovir': ['Acyclovir', 'Famciclovir', 'Penciclovir'],
    'Famciclovir': ['Acyclovir', 'Valacyclovir', 'Penciclovir'],
    'Penciclovir': ['Acyclovir', 'Valacyclovir', 'Famciclovir'],
    'Sildenafil': ['Tadalafil', 'Vardenafil', 'Avanafil'],
    'Tadalafil': ['Sildenafil', 'Vardenafil', 'Avanafil'],
    'Vardenafil': ['Sildenafil', 'Tadalafil', 'Avanafil'],
    'Avanafil': ['Sildenafil', 'Tadalafil', 'Vardenafil'],
    'Hydrochlorothiazide': ['Chlorthalidone', 'Indapamide', 'Metolazone'],
    'Chlorthalidone': ['Hydrochlorothiazide', 'Indapamide', 'Metolazone'],
    'Indapamide': ['Hydrochlorothiazide', 'Chlorthalidone', 'Metolazone'],
    'Metolazone': ['Hydrochlorothiazide', 'Chlorthalidone', 'Indapamide'],
    'Citalopram': ['Escitalopram', 'Fluoxetine', 'Sertraline'],
    'Escitalopram': ['Citalopram', 'Fluoxetine', 'Sertraline'],
    'Fluoxetine': ['Citalopram', 'Escitalopram', 'Sertraline'],
    'Sertraline': ['Citalopram', 'Escitalopram', 'Fluoxetine'],
    'Quinapril': ['Enalapril', 'Ramipril', 'Lisinopril'],
    'Ramipril': ['Enalapril', 'Quinapril', 'Lisinopril'],
    'Zaleplon': ['Zolpidem', 'Eszopiclone', 'Temazepam'],
    'Trazodone': ['Nefazodone', 'Desvenlafaxine', 'Bupropion'],
    'Nefazodone': ['Trazodone', 'Desvenlafaxine', 'Bupropion'],
    'Ketorolac': ['Naproxen', 'Ibuprofen', 'Aspirin'],
    'Oxycodone': ['Hydrocodone', 'Morphine', 'Fentanyl'],
    'Hydrocodone': ['Oxycodone', 'Morphine', 'Fentanyl'],
    'Morphine': ['Oxycodone', 'Hydrocodone', 'Fentanyl'],
    'Fentanyl': ['Oxycodone', 'Hydrocodone', 'Morphine'],
    'Loperamide': ['Diphenoxylate', 'Bismuth subsalicylate', 'Tincture of opium'],
    'Diphenoxylate': ['Loperamide', 'Bismuth subsalicylate', 'Tincture of opium'],
    'Bismuth subsalicylate': ['Loperamide', 'Diphenoxylate', 'Tincture of opium'],
    'Tincture of opium': ['Loperamide', 'Diphenoxylate', 'Bismuth subsalicylate'],
    'Metoclopramide': ['Prochlorperazine', 'Ondansetron', 'Domperidone'],
    'Prochlorperazine': ['Metoclopramide', 'Ondansetron', 'Domperidone'],
    'Ondansetron': ['Metoclopramide', 'Prochlorperazine', 'Domperidone'],
    'Domperidone': ['Metoclopramide', 'Prochlorperazine', 'Ondansetron'],
    'Methyldopa': ['Labetalol', 'Aldomet', 'Hydralazine'],
    'Aldomet': ['Methyldopa', 'Labetalol', 'Hydralazine'],
    'Hydralazine': ['Methyldopa', 'Labetalol', 'Aldomet'],
    'Bromocriptine': ['Cabergoline', 'Pergolide', 'Pramipexole'],
    'Cabergoline': ['Bromocriptine', 'Pergolide', 'Pramipexole'],
    'Pergolide': ['Bromocriptine', 'Cabergoline', 'Pramipexole'],
    'Pramipexole': ['Bromocriptine', 'Cabergoline', 'Pergolide'],
    'Amitriptyline': ['Nortriptyline', 'Doxepin', 'Desipramine'],
    'Clomiphene': ['Letrozole', 'Gonadotropins', 'Bromocriptine'],
    'Letrozole': ['Clomiphene', 'Gonadotropins', 'Bromocriptine'],
    'Gonadotropins': ['Clomiphene', 'Letrozole', 'Bromocriptine'],
    'Alendronate': ['Risedronate', 'Ibandronate', 'Zoledronic acid'],
    'Risedronate': ['Alendronate', 'Ibandronate', 'Zoledronic acid'],
    'Ibandronate': ['Alendronate', 'Risedronate', 'Zoledronic acid'],
    'Zoledronic acid': ['Alendronate', 'Risedronate', 'Ibandronate'],
    'Divalproex sodium': ['Valproic acid', 'Carbamazepine', 'Lamotrigine'],
    'Valproic acid': ['Divalproex sodium', 'Carbamazepine', 'Lamotrigine'],
    'Furosemide': ['Bumetanide', 'Torsemide', 'Ethacrynic acid'],
    'Bumetanide': ['Furosemide', 'Torsemide', 'Ethacrynic acid'],
    'Torsemide': ['Furosemide', 'Bumetanide', 'Ethacrynic acid'],
    'Ethacrynic acid': ['Furosemide', 'Bumetanide', 'Torsemide'],
    'Miconazole': ['Clotrimazole', 'Fluconazole', 'Ketoconazole'],
    'Clotrimazole': ['Miconazole', 'Fluconazole', 'Ketoconazole'],
    'Spironolactone': ['Eplerenone', 'Aldactone', 'Amiloride'],
    'Eplerenone': ['Spironolactone', 'Aldactone', 'Amiloride'],
    'Aldactone': ['Spironolactone', 'Eplerenone', 'Amiloride'],
    'Amiloride': ['Spironolactone', 'Eplerenone', 'Aldactone'],
    'Nystatin': ['Clotrimazole', 'Fluconazole', 'Miconazole'],
    'Dextromethorphan': ['Guaifenesin', 'Codeine', 'Brompheniramine'],
    'Guaifenesin': ['Dextromethorphan', 'Codeine', 'Brompheniramine'],
    'Codeine': ['Dextromethorphan', 'Guaifenesin', 'Brompheniramine'],
    'Brompheniramine': ['Dextromethorphan', 'Guaifenesin', 'Codeine'],
    'Folic acid': ['Leucovorin', 'Vitamin B12', 'Iron'],
    'Vitamin B12': ['Folic acid', 'Leucovorin', 'Iron'],
    'Leucovorin': ['Folic acid', 'Vitamin B12', 'Iron'],
    'Iron': ['Folic acid', 'Vitamin B12', 'Leucovorin'],
    'Methylphenidate': ['Amphetamine', 'Dexmethylphenidate', 'Lisdexamfetamine'],
    'Amphetamine': ['Methylphenidate', 'Dexmethylphenidate', 'Lisdexamfetamine'],
    'Dexmethylphenidate': ['Methylphenidate', 'Amphetamine', 'Lisdexamfetamine'],
    'Lisdexamfetamine': ['Methylphenidate', 'Amphetamine', 'Dexmethylphenidate'],
    'Bupropion': ['Venlafaxine', 'Duloxetine', 'Desvenlafaxine'],
    'Venlafaxine': ['Bupropion', 'Duloxetine', 'Desvenlafaxine'],
    'Duloxetine': ['Bupropion', 'Venlafaxine', 'Desvenlafaxine'],
    'Desvenlafaxine': ['Bupropion', 'Venlafaxine', 'Duloxetine'],
    'Ciprofloxacin': ['Levofloxacin', 'Moxifloxacin', 'Ofloxacin'],
    'Levofloxacin': ['Ciprofloxacin', 'Moxifloxacin', 'Ofloxacin'],
    'Moxifloxacin': ['Ciprofloxacin', 'Levofloxacin', 'Ofloxacin'],
    'Ofloxacin': ['Ciprofloxacin', 'Levofloxacin', 'Moxifloxacin'],
    'Rifampin': ['Isoniazid', 'Pyrazinamide', 'Ethambutol'],
    'Isoniazid': ['Rifampin', 'Pyrazinamide', 'Ethambutol'],
    'Pyrazinamide': ['Rifampin', 'Isoniazid', 'Ethambutol'],
    'Ethambutol': ['Rifampin', 'Isoniazid', 'Pyrazinamide'],
    'Quetiapine': ['Olanzapine', 'Risperidone', 'Aripiprazole'],
    'Olanzapine': ['Quetiapine', 'Risperidone', 'Aripiprazole'],
    'Risperidone': ['Quetiapine', 'Olanzapine', 'Aripiprazole'],
    'Aripiprazole': ['Quetiapine', 'Olanzapine', 'Risperidone'],
    'Sumatriptan': ['Rizatriptan', 'Naratriptan', 'Zolmitriptan'],
    'Rizatriptan': ['Sumatriptan', 'Naratriptan', 'Zolmitriptan'],
    'Naratriptan': ['Sumatriptan', 'Rizatriptan', 'Zolmitriptan'],
    'Zolmitriptan': ['Sumatriptan', 'Rizatriptan', 'Naratriptan'],
    'Benzonatate': ['Dextromethorphan', 'Guaifenesin', 'Codeine'],
    'Temazepam': ['Zolpidem', 'Eszopiclone', 'Triazolam'],
    'Eszopiclone': ['Zolpidem', 'Temazepam', 'Triazolam'],
    'Zolpidem': ['Eszopiclone', 'Temazepam', 'Triazolam'],
    'Triazolam': ['Zolpidem', 'Eszopiclone', 'Temazepam'],
    'Montelukast': ['Zafirlukast', 'Singulair', 'Cromolyn sodium'],
    'Zafirlukast': ['Montelukast', 'Singulair', 'Cromolyn sodium'],
    'Singulair': ['Montelukast', 'Zafirlukast', 'Cromolyn sodium'],
    'Cromolyn sodium': ['Montelukast', 'Zafirlukast', 'Singulair'],
    'Penicillin': ['Ampicillin', 'Amoxicillin', 'Cloxacillin'],
    'Ampicillin': ['Penicillin', 'Amoxicillin', 'Cloxacillin'],
    'Amoxicillin': ['Penicillin', 'Ampicillin', 'Cloxacillin'],
    'Cloxacillin': ['Penicillin', 'Ampicillin', 'Amoxicillin'],
    'Dexamethasone': ['Prednisone', 'Hydrocortisone', 'Methylprednisolone'],
    'Prednisone': ['Dexamethasone', 'Hydrocortisone', 'Methylprednisolone'],
    'Hydrocortisone': ['Dexamethasone', 'Prednisone', 'Methylprednisolone'],
    'Methylprednisolone': ['Dexamethasone', 'Prednisone', 'Hydrocortisone'],
    'Lithium': ['Sodium valproate', 'Carbamazepine', 'Lamotrigine'],
    'Sodium valproate': ['Lithium', 'Carbamazepine', 'Lamotrigine'],
    'Gabapentin': ['Pregabalin', 'Carbamazepine', 'Lamotrigine'],
    'Pregabalin': ['Gabapentin', 'Carbamazepine', 'Lamotrigine'],
    'Carbamazepine': ['Gabapentin', 'Pregabalin', 'Lamotrigine'],
    'Lamotrigine': ['Gabapentin', 'Pregabalin', 'Carbamazepine'],
    'Dantrolene': ['Baclofen', 'Carisoprodol', 'Cyclobenzaprine'],
    'Baclofen': ['Dantrolene', 'Carisoprodol', 'Cyclobenzaprine'],
    'Carisoprodol': ['Dantrolene', 'Baclofen', 'Cyclobenzaprine'],
    'Cyclobenzaprine': ['Dantrolene', 'Baclofen', 'Carisoprodol'],
    'Gabapentin enacarbil': ['Gabapentin', 'Pregabalin', 'Carbamazepine'],
    'Gabapentin': ['Gabapentin enacarbil', 'Pregabalin', 'Carbamazepine'],
    'Pregabalin': ['Gabapentin enacarbil', 'Gabapentin', 'Carbamazepine'],
    'Carbamazepine': ['Gabapentin enacarbil', 'Gabapentin', 'Pregabalin'],
    'Duloxetine': ['Venlafaxine', 'Bupropion', 'Desvenlafaxine'],
    'Ropinirole': ['Pramipexole', 'Rotigotine', 'Bromocriptine'],
    'Pramipexole': ['Ropinirole', 'Rotigotine', 'Bromocriptine'],
    'Rotigotine': ['Ropinirole', 'Pramipexole', 'Bromocriptine'],
    'Mirtazapine': ['Duloxetine', 'Venlafaxine', 'Bupropion'],
    'Zaleplon': ['Zolpidem', 'Eszopiclone', 'Temazepam'],
    'Methylphenidate': ['Amphetamine', 'Dexmethylphenidate', 'Lisdexamfetamine'],
    'Chlordiazepoxide': ['Diazepam', 'Clorazepate', 'Lorazepam'],
    'Diazepam': ['Chlordiazepoxide', 'Clorazepate', 'Lorazepam'],
    'Clorazepate': ['Chlordiazepoxide', 'Diazepam', 'Lorazepam'],
    'Lorazepam': ['Chlordiazepoxide', 'Diazepam', 'Clorazepate'],
    'Clonazepam': ['Diazepam', 'Lorazepam', 'Temazepam'],
    'Temazepam': ['Clonazepam', 'Diazepam', 'Lorazepam'],
    'Escitalopram': ['Citalopram', 'Fluoxetine', 'Sertraline'],
    'Sertraline': ['Citalopram', 'Fluoxetine', 'Escitalopram'],
    'Fluoxetine': ['Citalopram', 'Sertraline', 'Escitalopram'],
    'Amitriptyline': ['Doxepin', 'Nortriptyline', 'Desipramine'],
    'Doxepin': ['Amitriptyline', 'Nortriptyline', 'Desipramine'],
    'Nortriptyline': ['Amitriptyline', 'Doxepin', 'Desipramine'],
    'Desipramine': ['Amitriptyline', 'Doxepin', 'Nortriptyline'],
    'Adalimumab': ['Infliximab', 'Etanercept', 'Golimumab'],
    'Infliximab': ['Adalimumab', 'Etanercept', 'Golimumab'],
    'Etanercept': ['Adalimumab', 'Infliximab', 'Golimumab'],
    'Golimumab': ['Adalimumab', 'Infliximab', 'Etanercept'],
    'Atorvastatin': ['Rosuvastatin', 'Simvastatin', 'Pravastatin'],
    'Rosuvastatin': ['Atorvastatin', 'Simvastatin', 'Pravastatin'],
    'Simvastatin': ['Atorvastatin', 'Rosuvastatin', 'Pravastatin'],
    'Pravastatin': ['Atorvastatin', 'Rosuvastatin', 'Simvastatin'],
    'Metformin': ['Glipizide', 'Glyburide', 'Pioglitazone'],
    'Glipizide': ['Metformin', 'Glyburide', 'Pioglitazone'],
    'Glyburide': ['Metformin', 'Glipizide', 'Pioglitazone'],
    'Pioglitazone': ['Metformin', 'Glipizide', 'Glyburide'],
    'Furosemide': ['Bumetanide', 'Torsemide', 'Hydrochlorothiazide'],
    'Bumetanide': ['Furosemide', 'Torsemide', 'Hydrochlorothiazide'],
    'Torsemide': ['Furosemide', 'Bumetanide', 'Hydrochlorothiazide'],
    'Hydrochlorothiazide': ['Furosemide', 'Bumetanide', 'Torsemide'],
    'Amlodipine': ['Lisinopril', 'Benazepril', 'Diltiazem'],
    'Lisinopril': ['Amlodipine', 'Benazepril', 'Diltiazem'],
    'Benazepril': ['Amlodipine', 'Lisinopril', 'Diltiazem'],
    'Diltiazem': ['Amlodipine', 'Lisinopril', 'Benazepril'],
    'Sertraline': ['Citalopram', 'Fluoxetine', 'Escitalopram'],
    'Doxycycline': ['Tetracycline', 'Minocycline', 'Oxytetracycline'],
    'Tetracycline': ['Doxycycline', 'Minocycline', 'Oxytetracycline'],
    'Minocycline': ['Doxycycline', 'Tetracycline', 'Oxytetracycline'],
    'Oxytetracycline': ['Doxycycline', 'Tetracycline', 'Minocycline'],
    'Warfarin': ['Rivaroxaban', 'Apixaban', 'Dabigatran'],
    'Rivaroxaban': ['Warfarin', 'Apixaban', 'Dabigatran'],
    'Apixaban': ['Warfarin', 'Rivaroxaban', 'Dabigatran'],
    'Dabigatran': ['Warfarin', 'Rivaroxaban', 'Apixaban'],
    'Insulin': ['Glargine', 'Lispro', 'Aspart'],
    'Glargine': ['Insulin', 'Lispro', 'Aspart'],
    'Lispro': ['Insulin', 'Glargine', 'Aspart'],
    'Aspart': ['Insulin', 'Glargine', 'Lispro'],
    'Ranitidine': ['Famotidine', 'Nizatidine', 'Cimetidine'],
    'Famotidine': ['Ranitidine', 'Nizatidine', 'Cimetidine'],
    'Nizatidine': ['Ranitidine', 'Famotidine', 'Cimetidine'],
    'Cimetidine': ['Ranitidine', 'Famotidine', 'Nizatidine'],
    'Ketoconazole': ['Fluconazole', 'Itraconazole', 'Voriconazole'],
    'Fluconazole': ['Ketoconazole', 'Itraconazole', 'Voriconazole'],
    'Itraconazole': ['Ketoconazole', 'Fluconazole', 'Voriconazole'],
    'Voriconazole': ['Ketoconazole', 'Fluconazole', 'Itraconazole'],
    'Simvastatin': ['Atorvastatin', 'Rosuvastatin', 'Pravastatin'],
    'Lovastatin': ['Atorvastatin', 'Simvastatin', 'Pravastatin'],
    'Hydrochlorothiazide': ['Furosemide', 'Bumetanide', 'Torsemide'],
    'Rifabutin': ['Rifampin', 'Isoniazid', 'Ethambutol'],
    'Rifapentine': ['Rifampin', 'Isoniazid', 'Ethambutol'],
    'Thyroxine': ['Liothyronine', 'Levothyroxine', 'Triiodothyronine'],
    'Liothyronine': ['Thyroxine', 'Levothyroxine', 'Triiodothyronine'],
    'Levothyroxine': ['Thyroxine', 'Liothyronine', 'Triiodothyronine'],
    'Triiodothyronine': ['Thyroxine', 'Liothyronine', 'Levothyroxine'],
    'Clozapine': ['Olanzapine', 'Quetiapine', 'Risperidone'],
    'Zolpidem': ['Eszopiclone', 'Temazepam', 'Triazolam'],
    'Amphetamine': ['Methylphenidate', 'Dexmethylphenidate', 'Lisdexamfetamine'],
    'Amphetamine': ['Methylphenidate', 'Dexmethylphenidate', 'Lisdexamfetamine'],
    'Tramadol': ['Oxycodone', 'Hydrocodone', 'Morphine'],
    'Oxycodone': ['Tramadol', 'Hydrocodone', 'Morphine'],
    'Hydrocodone': ['Tramadol', 'Oxycodone', 'Morphine'],
    'Morphine': ['Tramadol', 'Oxycodone', 'Hydrocodone'],
    'Fentanyl': ['Sufentanil', 'Alfentanil', 'Remifentanil'],
    'Sufentanil': ['Fentanyl', 'Alfentanil', 'Remifentanil'],
    'Alfentanil': ['Fentanyl', 'Sufentanil', 'Remifentanil'],
    'Remifentanil': ['Fentanyl', 'Sufentanil', 'Alfentanil'],
    'Acetaminophen': ['Ibuprofen', 'Aspirin', 'Naproxen'],
    'Amoxicillin-Clavulanate': ['Ampicillin', 'Cefuroxime', 'Cefalexin'],
    'Azithromycin': ['Clarithromycin', 'Erythromycin', 'Doxycycline'],
    'Ceftriaxone': ['Cefotaxime', 'Cefepime', 'Meropenem'],
    'Ciprofloxacin': ['Levofloxacin', 'Ofloxacin', 'Moxifloxacin'],
    'Dexamethasone': ['Prednisolone', 'Hydrocortisone', 'Betamethasone'],
    'Domperidone': ['Metoclopramide', 'Prochlorperazine', 'Ondansetron'],
    'Enalapril': ['Lisinopril', 'Ramipril', 'Captopril'],
    'Gliclazide': ['Glipizide', 'Glyburide', 'Metformin'],
    'Hydrochlorothiazide': ['Chlorthalidone', 'Indapamide', 'Furosemide'],
    'Ketorolac': ['Ibuprofen', 'Naproxen', 'Aspirin'],
    'Lactulose': ['Sorbitol', 'Polyethylene Glycol', 'Magnesium Hydroxide'],
    'Levothyroxine': ['Liothyronine', 'Thyroxine', 'Triiodothyronine'],
    'Metronidazole': ['Tinidazole', 'Clindamycin', 'Secnidazole'],
    'Nifedipine': ['Amlodipine', 'Diltiazem', 'Verapamil'],
    'Nitrofurantoin': ['Trimethoprim-Sulfamethoxazole', 'Ciprofloxacin', 'Amoxicillin'],
    'Paracetamol-Caffeine': ['Paracetamol', 'Aspirin', 'Ibuprofen'],
    'Phenobarbital': ['Primidone', 'Phenytoin', 'Valproic acid'],
    'Prednisone': ['Methylprednisolone', 'Dexamethasone', 'Hydrocortisone'],
    'Propranolol': ['Atenolol', 'Metoprolol', 'Bisoprolol'],
    'Quinine': ['Chloroquine', 'Artemether-Lumefantrine', 'Dihydroartemisinin'],
    'Ranitidine': ['Famotidine', 'Omeprazole', 'Esomeprazole'],
    'Sodium Bicarbonate': ['Potassium Bicarbonate', 'Sodium Acetate', 'Sodium Citrate'],
    'Sulfamethoxazole-Trimethoprim': ['Ciprofloxacin', 'Amoxicillin', 'Doxycycline'],
    'Tamsulosin': ['Alfuzosin', 'Silodosin', 'Terazosin'],
    'Tetracycline': ['Doxycycline', 'Minocycline', 'Oxytetracycline'],
    'Ursodiol': ['Chenodiol', 'Lactulose', 'Cholestyramine'],
    'Valproate': ['Carbamazepine', 'Gabapentin', 'Lamotrigine'],
    'Vitamin D3': ['Vitamin D2', 'Calcium', 'Magnesium'],
    'Warfarin': ['Rivaroxaban', 'Apixaban', 'Dabigatran'],
    'Zaleplon': ['Zolpidem', 'Eszopiclone', 'Temazepam'],
    'Benzylpenicillin': ['Ampicillin', 'Amoxicillin', 'Cloxacillin'],
    'Clindamycin': ['Lincomycin', 'Erythromycin', 'Metronidazole'],
    'Hydrocodone': ['Oxycodone', 'Morphine', 'Tramadol'],
    'Morphine': ['Fentanyl', 'Oxycodone', 'Methadone'],
    'Nitroglycerin': ['Isosorbide Dinitrate', 'Isosorbide Mononitrate', 'Amlodipine'],
    'Omeprazole': ['Esomeprazole', 'Lansoprazole', 'Pantoprazole'],
    'Pantoprazole': ['Omeprazole', 'Esomeprazole', 'Rabeprazole'],
    'Sertraline': ['Fluoxetine', 'Citalopram', 'Escitalopram'],
    'Trazodone': ['Duloxetine', 'Venlafaxine', 'Bupropion'],
    'Zolpidem': ['Eszopiclone', 'Temazepam', 'Triazolam'],
    'Acetylcysteine': ['Guaifenesin', 'Ambroxol', 'Bromhexine'],
    'Bromhexine': ['Ambroxol', 'Guaifenesin', 'Acetylcysteine'],
    'Cefalexin': ['Cefuroxime', 'Ceftriaxone', 'Amoxicillin'],
    'Colchicine': ['Indomethacin', 'Ibuprofen', 'Naproxen'],
    'Fluconazole': ['Itraconazole', 'Ketoconazole', 'Voriconazole'],
    'Isosorbide Dinitrate': ['Nitroglycerin', 'Isosorbide Mononitrate', 'Amlodipine'],
    'Lansoprazole': ['Omeprazole', 'Pantoprazole', 'Rabeprazole'],
    'Methotrexate': ['Azathioprine', 'Cyclophosphamide', 'Leucovorin'],
    'Phenylephrine': ['Pseudoephedrine', 'Oxymetazoline', 'Cetirizine'],
    'Rivaroxaban': ['Apixaban', 'Dabigatran', 'Warfarin'],
    'Terbinafine': ['Griseofulvin', 'Clotrimazole', 'Fluconazole'],
    'Vitamin B12': ['Folic Acid', 'Vitamin B6', 'Vitamin D'],
    'Zinc Sulfate': ['Zinc Gluconate', 'Zinc Acetate', 'Zinc Citrate'],
    'Citalopram': ['Escitalopram', 'Sertraline', 'Fluoxetine'],
    'Clofarabine': ['Fludarabine', 'Cyclophosphamide', 'Gemcitabine'],
    'Chloroquine': ['Artemether-Lumefantrine', 'Quinine', 'Dihydroartemisinin'],
    'Artemether-Lumefantrine': ['Chloroquine', 'Quinine', 'Dihydroartemisinin'],
    'Betamethasone': ['Dexamethasone', 'Hydrocortisone', 'Prednisone'],
    'Cefepime': ['Ceftriaxone', 'Cefotaxime', 'Meropenem'],
    'Duloxetine': ['Venlafaxine', 'Bupropion', 'Desvenlafaxine'],
    'Etodolac': ['Ibuprofen', 'Naproxen', 'Aspirin'],
    'Mefloquine': ['Artemether-Lumefantrine', 'Quinine', 'Dihydroartemisinin'],
    'Prochlorperazine': ['Metoclopramide', 'Domperidone', 'Ondansetron'],
    'Raloxifene': ['Tamoxifen', 'Anastrozole', 'Letrozole'],
    'Sildenafil': ['Tadalafil', 'Vardenafil', 'Avanafil'],
    'Sitagliptin': ['Linagliptin', 'Saxagliptin', 'Metformin'],
    'Tramadol': ['Oxycodone', 'Hydrocodone', 'Morphine'],
    'Valacyclovir': ['Acyclovir', 'Famciclovir', 'Ganciclovir'],
    'Voriconazole': ['Fluconazole', 'Itraconazole', 'Ketoconazole'],
};

export default medicationAlternatives;
