export const casesData = [
    {
        "description": "A middle-aged female presents with a progressively enlarging, itchy papular lesion that initially appeared as a small, non-purulent (no pus) and non-bleeding pimple, which has since significantly increased in size.",
        "image_url": "https://pbs.twimg.com/media/GZJOOeRWUAE_-yU?format=jpg&name=900x900"
    },
    {
        "description": "Patient with unknown serostatus presents with a 3-day history of localized, unilateral chest rash characterized by burning and pruritic sensations, confined to one side of the body without midline crossover.",
        "image_url": "https://pbs.twimg.com/media/GZDKAehWgAAd7pn?format=jpg&name=small"
    },
    {
        "description": "After using lightening creams for about 3 years. She presents with this rash localized on that region.",
        "image_url": "https://pbs.twimg.com/media/GY8Z0BeXwAAHbZ1?format=jpg&name=small"
    },
    {
        "description": "86/f presented with sudden onset DIB associated with cough and chest pain. Saturation 76-80% on room air, PR-110bpm. Likely diagnosis? What is your next step in management?",
        "image_url": "https://pbs.twimg.com/media/GQbmMEJWEAAr414?format=jpg&name=small"
    },
    {
        "description": "26yM presents with skin lesions that are nodular and deep in skin, some discharging pus. Has numbness in the legs, fingers, toes & face deformity as shown below. These have been on for 5 years; he has moved in all witch doctors and traditional healers without improvement. Dx & mgt.",
        "image_url": "https://pbs.twimg.com/media/GPP1_z6bYAAGw4I?format=jpg&name=small, https://pbs.twimg.com/media/GPPvMUYaAAE23qI?format=jpg&name=small"
    },
     {
        "description": "A previously healthy 11-month-old girl presented to the emergency department with a 2-week history of progressively worsening dysphagia and cough. Her heart rate was 168 beats per minute, respiratory rate 33 breaths per minute, and oxygen saturation 100% while she was breathing ambient air. On physical examination, the patient was noted to be in acute distress. Irregular breathing and wheezing were observed. A chest radiograph showed a foreign body with a “halo” or “double-ring” sign — a finding that differentiates button batteries from coins — in the cervical esophagus (Panel A). Peripheral corrosion of the battery was also noted (Panel A, arrow). An urgent upper endoscopy was performed. The battery was removed, and no overt mucosal trauma or bleeding was noted. Approximately 10 hours after the procedure, torrential hematemesis and hemorrhagic shock developed. During emergency surgical exploration, no source of bleeding was initially identified, but intraoperative angiography revealed a fistula between the esophagus, which was dilated, and the left common carotid artery (Panel B, arrow). The artery was ligated, and hemostasis was achieved. Ingested or aspirated button batteries require prompt identification and removal owing to the risks of tissue necrosis, perforation, and fistula development. The patient was discharged home 32 days after the initial procedure, with no neurologic or functional deficits.",
        "image-url": "https://www.nejm.org/cms/10.1056/NEJMicm2310606/asset/a9afdd93-e053-4150-8678-1011d4587567/assets/images/large/nejmicm2310606_f1.jpg, https://www.nejm.org/cms/10.1056/NEJMicm2310606/asset/a9afdd93-e053-4150-8678-1011d4587567/assets/images/large/nejmicm2310606_f1.jpg"
    },    {
        "description": "83 yr old female with no known chronic illness presented with 1/12 hx of productive cough associated with on and off fevers, weight loss and anorexia. Recently reported right sided chest pain. Labs: WBC⬆️⬆️, neut⬆️⬆️... likely dx?",
        "image-url": "https://pbs.twimg.com/media/GPJnXAzXsAADi8M?format=jpg&name=small"
    },    {
        "description": "28yr/M HIV seropositive started ART 18months ago but later stopped 4months ago. presented with dry cough associated with evening fevers and severe weight loss. CD4 195cells, Hb 7g/dl, urine TB LAM positive. O/E is wasted with cervical lymphadenopathy measuring 3cm each. Dx &Mgt",
        "image-url": "https://pbs.twimg.com/media/GOwornQXUAIMvjg?format=jpg&name=small"
    },    {
        "description": "49yrM HIV seropositive on ART completed AntiTBs 2years ago. Presented with DIB, coughing blood and evening fevers. Genexpert no MTB detected, Urine TB LAM faint positive ",
        "image-url": ""
    },    {
        "description": "26y/M presents with DIB, no cough,fever, loss of weight or smoking. HIV seronegative, no known chronic illness. He reports a hlo head injury 2°RTA about 1.5 yrs ago which was managed. On thoracocentesis black oily fluid 6litres is drained. ",
        "image-url": ""
    },    {
        "description": "11yr/F living with Sickle cell disease presents with pointed zygomatic swelling that has increased gradually over 1month. No h/o trauma or fever. O/E Firm, non tender with shinny tip. no lymphadenopathy, mouth ulcer or missing tooth. Dx & mgt",
        "image-url": ""
    },    {
        "description": "60yr/M came in with these fungating lesions for 18months, started as nodules with punctate surface non painful and no itching. HIV -ve. They are secreting whitish mucus. Histology examination H & E stain shown dermal Proliferation of spindle cells forming slit like spaces  and RBC extravasation",
        "image-url": ""
    },    {
        "description": "18/M who is a refugee from S.Sudan but currently in P7 boarding school in Uganda, developed body pain, headache, fever and weakness 5days ago. Sent him where he was given paracetamol. He developed yellow eyes and became unconscious. Today GCS 5/15 with deep jaundice, yellow colored urine and intractable hiccups. No abdominal tenderness or distention HepSAg -Ve, B/S- No Malaria parasites seen. Liver function tests -slightly elevated liver enzymes with very high total bilirubin. CBC hb-15g/dl PLT-395",
        "image-url": ""
    },    {
        "description": "15y/M well untill 3mth ago when he was managed of meningitis. 1mth later he developed swelling of scalp, convulsions, confusion with episodes of syncope and left sided weakness. OE wasted, irritable,scalp edema tender and pitting, GCS 15/15. #GuluRRH",
        "image-url": "https://pbs.twimg.com/ext_tw_video_thumb/1768290629111476224/pu/img/1PKaV0t--bmAbRVR?format=jpg&name=900x900"
    },    {
        "description": "24y/F with RHD(Rheumatic Heart Disease) presents with vomiting, generalized abdominal pain followed by distension and failure to pass stool. Dx and approach",
        "image-url": "https://pbs.twimg.com/media/GIjqiDuWQAE1_KK?format=jpg&name=900x900"
    },    {
        "description": "62y/M  with copious sputum about 2 cups everyday and fevers. Managed of PTB with no Improvement was refered to #MubendeRRH with SPO2 80% on room Air",
        "image-url": "https://pbs.twimg.com/media/F3riDLQXEAAdnxf?format=jpg&name=small"
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    },    {
        "description": "",
        "image-url": ""
    }
]
