export const drugOptions = [
    'Aspirin',
    'Ibuprofen',
    'Acetaminophen',
    'Amoxicillin',
    'Albuterol',
    'Atorvastatin',
    'Lisinopril',
    'Metformin',
    'Simvastatin',
    'Omeprazole',
    'Levothyroxine',
    'Gabapentin',
    'Sertraline',
    'Citalopram',
    'Venlafaxine',
    'Fluoxetine',
    'Hydrochlorothiazide',
    'Metoprolol',
    'Amlodipine',
    'Furosemide',
    'Warfarin',
    'Clopidogrel',
    'Tamsulosin',
    'Losartan',
    'Pantoprazole',
    'Bupropion',
    'Zolpidem',
    'Duloxetine',
    'Rosuvastatin',
    'Ciprofloxacin',
    'Nitrofurantoin',
    'Hydrocodone',
    'Tramadol',
    'Oxycodone',
    'Morphine',
    'Prednisone',
    'Benzonatate',
    'Dexamethasone',
    'Atenolol',
    'Candesartan',
    'Esomeprazole',
    'Clonazepam',
    'Lorazepam',
    'Trazodone',
    'Mirtazapine',
    'Ranitidine',
    'Cetirizine',
    'Levocetirizine',
    'Diphenhydramine',
    'Loratadine',
    'Budesonide',
    'Fluticasone',
    'Montelukast',
    'Salbutamol',
    'Zafirlukast',
    'Naproxen',
    'Diclofenac',
    'Ketorolac',
    'Celecoxib',
    'Indomethacin',
    'Mefenamic Acid',
    'Dexamethasone',
    'Topiramate',
    'Carbamazepine',
    'Lamotrigine',
    'Levetiracetam',
    'Valproate',
    'Ethosuximide',
    'Oxcarbazepine',
    'Phenytoin',
    'Clonidine',
    'Quetiapine',
    'Olanzapine',
    'Risperidone',
    'Aripiprazole',
    'Lurasidone',
    'Ziprasidone',
    'Paliperidone',
    'Haloperidol',
    'Chlorpromazine',
    'Thioridazine',
    'Divalproex',
    'Buspirone',
    'Propranolol',
    'Carvedilol',
    'Nadolol',
    'Timolol',
    'Diltiazem',
    'Verapamil',
    'Fentanyl',
    'Methadone',
    'Buprenorphine',
    'Naltrexone',
    'Naloxone',
    'Acetazolamide',
    'Lithium',
    'Sodium Valproate',
    'Baclofen',
    'Cyclobenzaprine',
    'Methocarbamol',
    'Carisoprodol',
    'Tizanidine',
    'Pregabalin',
    'Hydroxychloroquine',
    'Azithromycin',
    'Clarithromycin',
    'Doxycycline',
    'Minocycline',
    'Amoxicillin/Clavulanate',
    'Cefdinir',
    'Ceftriaxone',
    'Cefuroxime',
    'Vancomycin',
    'Metronidazole',
    'Nystatin',
    'Fluconazole',
    'Itraconazole',
    'Voriconazole',
    'Clotrimazole',
    'Ketoconazole',
    'Anastrozole',
    'Tamoxifen',
    'Letrozole',
    'Trastuzumab',
    'Rituximab',
    'Bevacizumab',
    'Pembrolizumab',
    'Nivolumab',
    'Carboplatin',
    'Cisplatin',
    'Docetaxel',
    'Paclitaxel',
    'Vincristine',
    'Vinblastine',
    'Doxorubicin',
    'Epirubicin',
    'Fluorouracil',
    'Capecitabine',
    'Gemcitabine',
    'Lapatinib',
    'Imatinib',
    'Dasatinib',
    'Nilotinib',
    'Bortezomib',
    'Lenalidomide',
    'Thalidomide',
    'Rituximab',
    'Azacitidine',
    'Decitabine',
    'Dexamethasone',
    'Atezolizumab',
    'Durvalumab',
    'Trastuzumab',
    'Bevacizumab',
    'Adalimumab',
    'Etanercept',
    'Infliximab',
    'Golimumab',
    'Certolizumab',
    'Methotrexate',
    'Cyclophosphamide',
    'Hydroxyurea',
    'Busulfan',
    'Mercaptopurine',
    'Azathioprine',
    'Mycophenolate Mofetil',
    'Tacrolimus',
    'Cyclosporine',
    'Sirolimus',
    'Everolimus',
    'Corticosteroids',
    'Phenobarbital',
    'Secobarbital',
    'Amobarbital',
    'Barbiturates',
    'Chlordiazepoxide',
    'Diazepam',
    'Lorazepam',
    'Oxazepam',
    'Temazepam',
    'Midazolam',
    'Clonazepam',
    'Quazepam',
    'Eszopiclone',
    'Zaleplon',
    'Zolpidem',
    'Doxepin',
    'Desvenlafaxine',
    'Silexan',
    'Milnacipran',
    'Frovatriptan',
    'Rizatriptan',
    'Sumatriptan',
    'Naratriptan',
    'Eletriptan',
    'Amitriptyline',
    'Nortriptyline',
    'Duloxetine',
    'Venlafaxine',
    'Gabapentin',
    'Pregabalin',
    'Topiramate',
    'Lamotrigine',
    'Citalopram',
    'Escitalopram',
    'Paroxetine',
    'Sertraline',
    'Fluoxetine',
    'Tranylcypromine',
    'Phenelzine',
    'Isocarboxazid',
    'Selegiline',
    'Lithium Carbonate',
    'Valproic Acid',
    'Methylphenidate',
    'Amphetamine',
    'Dexmethylphenidate',
    'Atomoxetine',
    'Lisdexamfetamine',
    'Modafinil',
    'Armodafinil',
    'Caffeine',
    'Theophylline',
    'Nicotine',
    'Varenicline',
    'Bupropion',
    'Naltrexone',
    'Methadone',
    'Buprenorphine',
    'Carfentanil',
    'Sufentanil',
    'Fentanyl',
    'Dihydrocodeine',
    'Hydromorphone',
    'Oxycodone',
    'Codeine',
    'Tramadol',
    'Morphine',
    'Meperidine',
    'Pethidine',
    'Loperamide',
    'Diphenoxylate',
    'Cholestyramine',
    'Colesevelam',
    'Gemfibrozil',
    'Fenofibrate',
    'Niacin',
    'Omega-3-acid Ethyl Esters',
    'Ezetimibe',
    'Bile Acid Sequestrants',
    'Statins',
    'PCSK9 Inhibitors',
    'Mipomersen',
    'Alirocumab',
    'Evolocumab',
    'Prazosin',
    'Doxazosin',
    'Terazosin',
    'Alfuzosin',
    'Tamsulosin',
    'Silodosin',
    'Latanoprost',
    'Bimatoprost',
    'Travoprost',
    'Timolol',
    'Brimonidine',
    'Carbachol',
    'Pilocarpine',
    'Dorzolamide',
    'Acetazolamide',
    'Osmotic Agents',
    'Fluorescein',
    'Conjunctival Agents',
    'Systemic Agents',
    'Atropine',
    'Tropicamide',
    'Cyclopentolate',
    'Phenylephrine',
    'Proparacaine',
    'Benzalkonium Chloride',
    'Sodium Hyaluronate',
    'Bromfenac',
    'Ketorolac',
    'Diclofenac',
    'Fluocinolone',
    'Dexamethasone',
    'Triamcinolone',
    'Prednisolone',
    'Hydrocortisone',
    'Betamethasone',
    'Fluticasone',
    'Mometasone',
    'Budesonide',
    'Beclomethasone',
    'Formoterol',
    'Salbutamol',
    'Salmeterol',
    'Vilanterol',
    'Olodaterol',
    'Indacaterol',
    'Umeclidinium',
    'Aclidinium',
    'Tiotropium',
    'Ipratropium',
    'Glycopyrrolate',
    'Theophylline',
    'Montelukast',
    'Zafirlukast',
    'Mepolizumab',
    'Reslizumab',
    'Benralizumab',
    'Omalizumab',
    'Palivizumab',
    'Ribavirin',
    'Sofosbuvir',
    'Ledipasvir',
    'Velpatasvir',
    'Glecaprevir',
    'Pibrentasvir',
    'Interferon Alfa',
    'Peginterferon Alfa',
    'Adefovir',
    'Entecavir',
    'Lamivudine',
    'Zidovudine',
    'Stavudine',
    'Didanosine',
    'Abacavir',
    'Tenofovir',
    'Emtricitabine',
    'Rilpivirine',
    'Doravirine',
    'Etravirine',
    'Nevirapine',
    'Efavirenz',
    'Lopinavir',
    'Ritonavir',
    'Saquinavir',
    'Indinavir',
    'Nelfinavir',
    'Fosamprenavir',
    'Atazanavir',
    'Darunavir',
    'Tipranavir',
    'Cobicistat',
    'Zalcitabine',
    'Ribavirin',
    'Daclatasvir',
    'Simeprevir',
    'Sofosbuvir',
    'Ledipasvir',
    'Velpatasvir',
    'Glecaprevir',
    'Pibrentasvir',
    'Adefovir',
    'Entecavir',
    'Lamivudine',
    'Zidovudine',
    'Stavudine',
    'Didanosine',
    'Abacavir',
    'Tenofovir',
    'Emtricitabine',
    'Rilpivirine',
    'Doravirine',
    'Etravirine',
    'Nevirapine',
    'Efavirenz',
    'Lopinavir',
    'Ritonavir',
    'Saquinavir',
    'Indinavir',
    'Nelfinavir',
    'Fosamprenavir',
    'Atazanavir',
    'Darunavir',
    'Tipranavir',
    'Cobicistat',
    'Zalcitabine',
    'Peginterferon',
    'Amiodarone',
    'Sotalol',
    'Dronedarone',
    'Adenosine',
    'Digoxin',
    'Diltiazem',
    'Verapamil',
    'Nifedipine',
    'Amlodipine',
    'Nitrates',
    'Nitroglycerin',
    'Isosorbide Dinitrate',
    'Isosorbide Mononitrate',
    'Ranolazine',
    'Hydralazine',
    'Minoxidil',
    'Lisinopril',
    'Enalapril',
    'Ramipril',
    'Captopril',
    'Benazepril',
    'Quinapril',
    'Fosinopril',
    'Moexipril',
    'Trandolapril',
    'Angiotensin Receptor Blockers',
    'Losartan',
    'Valsartan',
    'Irbesartan',
    'Candesartan',
    'Telmisartan',
    'Azilsartan',
    'Aliskiren',
    'Dexamethasone',
    'Prednisone',
    'Fludrocortisone',
    'Hydrocortisone',
    'Corticosteroids',
    'Methotrexate',
    'Cyclophosphamide',
    'Mycophenolate Mofetil',
    'Tacrolimus',
    'Sirolimus',
    'Everolimus',
    'Bortezomib',
    'Lenalidomide',
    'Thalidomide',
    'Azacitidine',
    'Decitabine',
    'Dabrafenib',
    'Trametinib',
    'Vemurafenib',
    'Cobimetinib',
    'Pazopanib',
    'Sorafenib',
    'Sunitinib',
    'Regorafenib',
    'Nivolumab',
    'Pembrolizumab',
    'Ipilimumab',
    'Tremelimumab',
    'Bevacizumab',
    'Atezolizumab',
    'Durvalumab',
    'Trastuzumab',
    'Rituximab',
    'Alemtuzumab',
    'Cetuximab',
    'Panitumumab',
    'Gemtuzumab',
    'Ziv-aflibercept',
    'Blinatumomab',
    'Daratumumab',
    'Elotuzumab',
    'Inotuzumab',
    'Obinutuzumab',
    'Moxetumomab',
    'Lemtrada',
    'Ustekinumab',
    'Secukinumab',
    'Adalimumab',
    'Etanercept',
    'Infliximab',
    'Golimumab',
    'Certolizumab',
    'Methotrexate',
    'Cyclophosphamide',
    'Azathioprine',
    'Mycophenolate Mofetil',
    'Tacrolimus',
    'Sirolimus',
    'Everolimus',
    'Thalidomide',
    'Bortezomib',
    'Dexamethasone',
    'Lenalidomide',
    'Azacitidine',
    'Decitabine',
    'Omalizumab',
    'Mepolizumab',
    'Reslizumab',
    'Benralizumab',
    'Dupilumab',
    'Baricitinib',
    'Tofacitinib',
    'Filgotinib',
    'Upadacitinib',
    'Apremilast',
    'Ruxolitinib',
    'Fedratinib',
    'Jakafi',
    'Gilteritinib',
    'Ivosidenib',
    'Enasidenib',
    'Olaratumab',
    'Pazopanib',
    'Lenvatinib',
    'Cabozantinib',
    'Ponatinib',
    'Dasatinib',
    'Nilotinib',
    'Bosutinib',
    'Imatinib',
    'Crizotinib',
    'Ceritinib',
    'Alectinib',
    'Brigatinib',
    'Lorlatinib',
    'Entrectinib',
    'Selpercatinib',
    'Pralsetinib',
    'Tazemetostat',
    'Entrectinib',
    'Fosnetupitant',
    'Netupitant',
    'Aprepitant',
    'Palonosetron',
    'Granisetron',
    'Dolasetron',
    'Ondansetron',
    'Nabilone',
    'Dronabinol',
    'Gabapentin',
    'Pregabalin',
    'Methylprednisolone',
    'Prednisolone',
    'Budesonide',
    'Hydrocortisone',
    'Dexamethasone',
    'Methylprednisolone',
    'Triamcinolone',
    'Desoximetasone',
    'Fluocinolone',
    'Fluticasone',
    'Budesonide',
    'Clobetasol',
    'Halobetasol',
    'Betamethasone',
    'Mometasone',
    'Triamcinolone',
    'Corticosteroids',
    'Allopurinol',
    'Febuxostat',
    'Probenecid',
    'Sulfinpyrazone',
    'Colchicine',
    'Uricosurics',
    'Aspirin',
    'Ibuprofen',
    'Naproxen',
    'Diclofenac',
    'Celecoxib',
    'Etodolac',
    'Ketorolac',
    'Indomethacin',
    'Meloxicam',
    'Piroxicam',
    'Valdecoxib',
    'Rofecoxib',
    'Hydrocodone',
    'Oxycodone',
    'Tramadol',
    'Morphine',
    'Fentanyl',
    'Methadone',
    'Buprenorphine',
    'Nalbuphine',
    'Pentazocine',
    'Meperidine',
    'Tapentadol',
    'Chlorpheniramine',
    'Diphenhydramine',
    'Promethazine',
    'Dextromethorphan',
    'Hydroxyzine',
    'Loratadine',
    'Cetirizine',
    'Levocetirizine',
    'Fexofenadine',
    'Brompheniramine',
    'Desloratadine',
    'Carbinoxamine',
    'Dexchlorpheniramine',
    'Phenylephrine',
    'Pseudoephedrine',
    'Oxymetazoline',
    'Xylometazoline',
    'Fluticasone',
    'Budesonide',
    'Mometasone',
    'Beclomethasone',
    'Triamcinolone',
    'Hydrocodone',
    'Dextromethorphan',
    'Guaifenesin',
    'Acetylcysteine',
    'Codeine',
    'Chlorpheniramine',
    'Loratadine',
    'Cetirizine',
    'Levocetirizine',
    'Dexchlorpheniramine',
    'Diphenhydramine',
    'Promethazine',
    'Fexofenadine',
    'Desloratadine',
    'Brompheniramine',
    'Hydroxyzine',
    'Aspirin',
    'Acetaminophen',
    'Ibuprofen',
    'Naproxen',
    'Diclofenac',
    'Celecoxib',
    'Etodolac',
    'Ketorolac',
    'Indomethacin',
    'Meloxicam',
    'Piroxicam',
    'Rofecoxib',
    'Valdecoxib',
    'Methadone',
    'Buprenorphine',
    'Fentanyl',
    'Oxycodone',
    'Tramadol',
    'Hydromorphone',
    'Codeine',
    'Morphine',
    'Naloxone',
    'Naltrexone',
    'Carbamazepine',
    'Gabapentin',
    'Pregabalin',
    'Valproate',
    'Topiramate',
    'Phenytoin',
    'Oxcarbazepine',
    'Eslicarbazepine',
    'Lamotrigine',
    'Divalproex',
    'Levetiracetam',
    'Baclofen',
    'Carisoprodol',
    'Cyclobenzaprine',
    'Tizanidine',
    'Soma',
    'Flexeril',
    'Robaxin',
    'Zanaflex',
    'Skeletal Muscle Relaxants',
    'Buprenorphine',
    'Methadone',
    'Naltrexone',
    'Naloxone',
    'Carfentanil',
    'Fentanyl',
    'Hydrocodone',
    'Oxycodone',
    'Tramadol',
    'Morphine',
    'Codeine',
    'Sufentanil',
    'Dihydrocodeine',
    'Tapentadol',
    'Buprenorphine',
    'Sufentanil',
    'Dihydrocodeine',
    'Hydromorphone',
    'Oxycodone',
    'Fentanyl',
    'Tapentadol',
    'Carfentanil',
    'Methadone',
    'Tramadol',
    'Benzodiazepines',
    'Buspirone',
    'Zolpidem',
    'Eszopiclone',
    'Zaleplon',
    'Ramelteon',
    'Doxepin',
    'Suvorexant',
    'Melatonin',
    'Phenobarbital',
    'Secobarbital',
    'Amobarbital',
    'Barbiturates',
    'Chlordiazepoxide',
    'Diazepam',
    'Lorazepam',
    'Oxazepam',
    'Temazepam',
    'Clonazepam',
    'Midazolam',
    'Triazolam',
    'Nitrazepam',
    'Flurazepam',
    'Estazolam',
    'Ramelteon',
    'Rizatriptan',
    'Sumatriptan',
    'Naratriptan',
    'Zolmitriptan',
    'Eletriptan',
    'Frovatriptan',
    'Amitriptyline',
    'Nortriptyline',
    'Duloxetine',
    'Venlafaxine',
    'Gabapentin',
    'Pregabalin',
    'Topiramate',
    'Carbamazepine',
    'Lamotrigine',
    'Baclofen',
    'Cyclobenzaprine',
    'Tizanidine',
    'Chronic Pain Medications',
    'Aspirin',
    'Acetaminophen',
    'Ibuprofen',
    'Naproxen',
    'Diclofenac',
    'Celecoxib',
    'Gabapentin',
    'Pregabalin',
    'Tramadol',
    'Morphine',
    'Hydrocodone',
    'Oxycodone',
    'Fentanyl',
    'Methadone',
    'Buprenorphine',
    'Naltrexone',
    'Naloxone',
    'Dihydrocodeine',
    'Carbamazepine',
    'Lamotrigine',
    'Topiramate',
    'Valproate',
    'Dexamethasone',
    'Methotrexate',
    'Cyclophosphamide',
    'Azathioprine',
    'Mycophenolate Mofetil',
    'Tacrolimus',
    'Sirolimus',
    'Everolimus',
    'Bortezomib',
    'Dexamethasone',
    'Lenalidomide',
    'Azacitidine',
    'Decitabine',
    'Dabrafenib',
    'Trametinib',
    'Vemurafenib',
    'Cobimetinib',
    'Pazopanib',
    'Sorafenib',
    'Sunitinib',
    'Regorafenib',
    'Nivolumab',
    'Pembrolizumab',
    'Ipilimumab',
    'Tremelimumab',
    'Bevacizumab',
    'Atezolizumab',
    'Durvalumab',
    'Trastuzumab',
    'Rituximab',
    'Alemtuzumab',
    'Cetuximab',
    'Panitumumab',
    'Gemtuzumab',
    'Ziv-aflibercept',
    'Blinatumomab',
    'Daratumumab',
    'Elotuzumab',
    'Inotuzumab',
    'Obinutuzumab',
    'Moxetumomab',
    'Lemtrada',
    'Ustekinumab',
    'Secukinumab',
    'Adalimumab',
    'Etanercept',
    'Infliximab',
    'Golimumab',
    'Certolizumab',
    'Methotrexate',
    'Cyclophosphamide',
    'Azathioprine',
    'Mycophenolate Mofetil',
    'Tacrolimus',
    'Sirolimus',
    'Everolimus',
    'Thalidomide',
    'Bortezomib',
    'Dexamethasone',
    'Lenalidomide',
    'Azacitidine',
    'Decitabine',
    'Omalizumab',
    'Mepolizumab',
    'Reslizumab',
    'Benralizumab',
    'Dupilumab',
    'Baricitinib',
    'Tofacitinib',
    'Filgotinib',
    'Upadacitinib',
    'Apremilast',
    'Ruxolitinib',
    'Fedratinib',
    'Jakafi',
    'Gilteritinib',
    'Ivosidenib',
    'Enasidenib',
    'Olaratumab',
    'Pazopanib',
    'Lenvatinib',
    'Cabozantinib',
    'Ponatinib',
    'Dasatinib',
    'Nilotinib',
    'Bosutinib',
    'Imatinib',
    'Crizotinib',
    'Ceritinib',
    'Alectinib',
    'Brigatinib',
    'Lorlatinib',
    'Entrectinib',
    'Selpercatinib',
    'Pralsetinib',
    'Tazemetostat',
    'Entrectinib',
    'Fosnetupitant',
    'Netupitant',
    'Aprepitant',
    'Palonosetron',
    'Granisetron',
    'Dolasetron',
    'Ondansetron',
    'Nabilone',
    'Dronabinol',
    'Gabapentin',
    'Pregabalin',
    'Methylprednisolone',
    'Prednisolone',
    'Budesonide',
    'Hydrocortisone',
    'Dexamethasone',
    'Methylprednisolone',
    'Triamcinolone',
    'Desoximetasone',
    'Fluocinolone',
    'Fluticasone',
    'Budesonide',
    'Clobetasol',
    'Halobetasol',
    'Betamethasone',
    'Mometasone',
    'Triamcinolone',
    'Corticosteroids',
        'Aspirin',
        'Ibuprofen',
        'Acetaminophen',
        'Amoxicillin',
        // New additions
        'Metformin',
        'Simvastatin',
        'Atorvastatin',
        'Rosuvastatin',
        'Levothyroxine',
        'Lisinopril',
        'Losartan',
        'Amiodarone',
        'Sotalol',
        'Dronedarone',
        'Furosemide',
        'Hydrochlorothiazide',
        'Spironolactone',
        'Clopidogrel',
        'Warfarin',
        'Rivaroxaban',
        'Apixaban',
        'Dabigatran',
        'Edoxaban',
        'Naproxen',
        'Diclofenac',
        'Celecoxib',
        'Etodolac',
        'Ketorolac',
        'Indomethacin',
        'Meloxicam',
        'Piroxicam',
        'Valdecoxib',
        'Rofecoxib',
        'Hydrocodone',
        'Oxycodone',
        'Tramadol',
        'Morphine',
        'Fentanyl',
        'Methadone',
        'Buprenorphine',
        'Nalbuphine',
        'Pentazocine',
        'Meperidine',
        'Tapentadol',
        'Gabapentin',
        'Pregabalin',
        'Topiramate',
        'Phenytoin',
        'Oxcarbazepine',
        'Eslicarbazepine',
        'Lamotrigine',
        'Divalproex',
        'Levetiracetam',
        'Baclofen',
        'Cyclobenzaprine',
        'Tizanidine',
        'Clonazepam',
        'Diazepam',
        'Lorazepam',
        'Alprazolam',
        'Temazepam',
        'Midazolam',
        'Buspirone',
        'Zolpidem',
        'Eszopiclone',
        'Ramelteon',
        'Suvorexant',
        'Melatonin',
        'Phenobarbital',
        'Secobarbital',
        'Amobarbital',
        'Barbiturates',
        'Amitriptyline',
        'Nortriptyline',
        'Duloxetine',
        'Venlafaxine',
        'Bupropion',
        'Mirtazapine',
        'Trazodone',
        'Desvenlafaxine',
        'Fluoxetine',
        'Paroxetine',
        'Sertraline',
        'Citalopram',
        'Escitalopram',
        'Lithium',
        'Stimulants',
        'Amphetamine',
        'Methylphenidate',
        'Dexmethylphenidate',
        'Lisdexamfetamine',
        'Atomoxetine',
        'Modafinil',
        'Armodafinil',
        'Naltrexone',
        'Naloxone',
        'Carbamazepine',
        'Valproate',
        'Hydroxyzine',
        'Diphenhydramine',
        'Chlorpheniramine',
        'Cetirizine',
        'Levocetirizine',
        'Fexofenadine',
        'Desloratadine',
        'Brompheniramine',
        'Oxymetazoline',
        'Pseudoephedrine',
        'Phenylephrine',
        'Nabilone',
        'Dronabinol',
        'Aprepitant',
        'Palonosetron',
        'Granisetron',
        'Dolasetron',
        'Ondansetron',
        'Clobetasol',
        'Fluticasone',
        'Budesonide',
        'Mometasone',
        'Triamcinolone',
        'Desoximetasone',
        'Fluocinolone',
        'Hydrocortisone',
        'Dexamethasone',
        'Prednisone',
        'Prednisolone',
        'Methylprednisolone',
        'Betamethasone',
        'Adalimumab',
        'Infliximab',
        'Etanercept',
        'Secukinumab',
        'Ustekinumab',
        'Dupilumab',
        'Baricitinib',
        'Tofacitinib',
        'Filgotinib',
        'Apremilast',
        'Ruxolitinib',
        'Fedratinib',
        'Jakafi',
        'Gilteritinib',
        'Ivosidenib',
        'Enasidenib',
        'Olaratumab',
        'Pazopanib',
        'Lenvatinib',
        'Cabozantinib',
        'Ponatinib',
        'Dasatinib',
        'Nilotinib',
        'Bosutinib',
        'Imatinib',
        'Crizotinib',
        'Ceritinib',
        'Alectinib',
        'Brigatinib',
        'Lorlatinib',
        'Entrectinib',
        'Selpercatinib',
        'Pralsetinib',
        'Tazemetostat',
        'Nivolumab',
        'Pembrolizumab',
        'Ipilimumab',
        'Trastuzumab',
        'Rituximab',
        'Alemtuzumab',
        'Cetuximab',
        'Panitumumab',
        'Gemtuzumab',
        'Ziv-aflibercept',
        'Blinatumomab',
        'Daratumumab',
        'Elotuzumab',
        'Inotuzumab',
        'Obinutuzumab',
        'Moxetumomab',
        'Lemtrada',
        'Tretinoin',
        'Bexarotene',
        'Thalidomide',
        'Lenalidomide',
        'Azacitidine',
        'Decitabine',
        'Bortezomib',
        'Methotrexate',
        'Cyclophosphamide',
        'Mycophenolate Mofetil',
        'Tacrolimus',
        'Sirolimus',
        'Everolimus',
        'Temsirolimus',
        'Arsenic Trioxide',
        'Busulfan',
        'Bleomycin',
        'Dactinomycin',
        'Doxorubicin',
        'Etoposide',
        'Vincristine',
        'Vinblastine',
        'Paclitaxel',
        'Docetaxel',
        'Gemcitabine',
        'Cyclophosphamide',
        'Ifosfamide',
        'Cisplatin',
        'Carboplatin',
        'Oxaliplatin',
        'Topotecan',
        'Irinotecan',
        'Fludarabine',
        'Cladribine',
        'Mercaptopurine',
        'Thioguanine',
        'Hydroxyurea',
        'Etoposide',
        'Rituximab',
        'Trastuzumab',
        'Bevacizumab',
        'Pembrolizumab',
        'Atezolizumab',
        'Durvalumab',
        'Nivolumab',
        'Ipilimumab',
        'Temozolomide',
        'Anastrozole',
        'Letrozole',
        'Exemestane',
        'Tamoxifen',
        'Raloxifene',
        'Bicalutamide',
        'Enzalutamide',
        'Abiraterone',
        'Palbociclib',
        'Ribociclib',
        'Apatinib',
        'Sorafenib',
        'Sunitinib',
        'Regorafenib',
        'Lapatinib',
        'Trametinib',
        'Dabrafenib',
        'Vemurafenib',
        'Osimertinib',
        'Neratinib',
        'Brentuximab',
        'Gemtuzumab',
        'Darzalex',
        'Elotuzumab',
        'Nivolumab',
        'Pembrolizumab',
        'Atezolizumab',
        'Durvalumab',
        'Ustekinumab',
        'Secukinumab',
        'Adalimumab',
        'Etanercept',
        'Infliximab',
        'Golimumab',
        'Certolizumab',
        'Methotrexate',
        'Cyclophosphamide',
        'Azathioprine',
        'Mycophenolate Mofetil',
        'Tacrolimus',
        'Sirolimus',
        'Everolimus',
        'Bortezomib',
        'Dexamethasone',
        'Lenalidomide',
        'Azacitidine',
        'Decitabine',
        'Dabrafenib',
        'Trametinib',
        'Vemurafenib',
        'Cobimetinib',
        'Pazopanib',
        'Sorafenib',
        'Sunitinib',
        'Regorafenib',
        'Nivolumab',
        'Pembrolizumab',
        'Ipilimumab',
        'Tremelimumab',
        'Bevacizumab',
        'Atezolizumab',
            // Existing drugs
            'Aspirin',
            'Ibuprofen',
            'Acetaminophen',
            'Amoxicillin',
            // New additions
            'Metformin',
            'Simvastatin',
            'Atorvastatin',
            'Levothyroxine',
            'Lisinopril',
            'Losartan',
            'Furosemide',
            'Clopidogrel',
            'Warfarin',
            'Rivaroxaban',
            'Naproxen',
            'Diclofenac',
            'Celecoxib',
            'Hydrocodone',
            'Oxycodone',
            'Tramadol',
            'Gabapentin',
            'Pregabalin',
            'Fluoxetine',
            'Sertraline',
            'Citalopram',
            'Escitalopram',
            'Bupropion',
            'Duloxetine',
            'Amitriptyline',
            'Hydroxyzine',
            'Cetirizine',
            'Levocetirizine',
            'Fexofenadine',
            'Diphenhydramine',
            'Loratadine',
            'Metoclopramide',
            'Omeprazole',
            'Esomeprazole',
            'Pantoprazole',
            'Ranitidine',
            'Famotidine',
            'Simethicone',
            'Loperamide',
            'Docusate Sodium',
            'Polyethylene Glycol',
            'Bisacodyl',
            'Senna',
            'Albuterol',
            'Budesonide',
            'Fluticasone',
            'Montelukast',
            'Salbutamol',
            'Ipratropium',
            'Theophylline',
            'Ciprofloxacin',
            'Levofloxacin',
            'Moxifloxacin',
            'Doxycycline',
            'Clindamycin',
            'Metronidazole',
            'Sulfamethoxazole/Trimethoprim',
            'Tetracycline',
            'Vancomycin',
            'Gentamicin',
            'Azithromycin',
            'Erythromycin',
            'Cephalexin',
            'Ceftriaxone',
            'Cefuroxime',
            'Amoxicillin/Clavulanate',
            'Rifampin',
            'Isoniazid',
            'Pyrazinamide',
            'Ethambutol',
            'Clofazimine',
            'Dapsone',
            'Leflunomide',
            'Methotrexate',
            'Azathioprine',
            'Mycophenolate Mofetil',
            'Cyclosporine',
            'Tacrolimus',
            'Sirolimus',
            'Prednisone',
            'Hydrocortisone',
            'Dexamethasone',
            'Bupropion',
            'Zolpidem',
            'Eszopiclone',
            'Ramelteon',
            'Buspirone',
            'Pregabalin',
            'Gabapentin',
            'Lithium',
            'Valproic Acid',
            'Carbamazepine',
            'Clonazepam',
            'Alprazolam',
            'Diazepam',
            'Temazepam',
            'Midazolam',
            'Nitrazepam',
            'Flurazepam',
            'Chlordiazepoxide',
            'Prazepam',
            'Buspirone',
            'Hydroxyzine',
            'Chlorpromazine',
            'Haloperidol',
            'Olanzapine',
            'Risperidone',
            'Quetiapine',
            'Aripiprazole',
            'Lurasidone',
            'Ziprasidone',
            'Clozapine',
            'Paliperidone',
            'Venlafaxine',
            'Desvenlafaxine',
            'Duloxetine',
            'Fluoxetine',
            'Paroxetine',
            'Sertraline',
            'Citalopram',
            'Escitalopram',
            'Amitriptyline',
            'Mirtazapine',
            'Trazodone',
            'Bupropion',
            'Modafinil',
            'Armodafinil',
            'Fentanyl',
            'Methadone',
            'Buprenorphine',
            'Naltrexone',
            'Naloxone',
            'Lidocaine',
            'Baclofen',
            'Cyclobenzaprine',
            'Tizanidine',
            'Methocarbamol',
            'Carisoprodol',
            'Orphenadrine',
            'Dantrolene',
            'Skeletal Muscle Relaxants',
            'Aspirin',
            'Clopidogrel',
            'Prasugrel',
            'Ticagrelor',
            'Warfarin',
            'Rivaroxaban',
            'Apixaban',
            'Dabigatran',
            'Edoxaban',
            'Nitroglycerin',
            'Isosorbide Mononitrate',
            'Isosorbide Dinitrate',
            'Digoxin',
            'Sotalol',
            'Amiodarone',
            'Dronedarone',
            'Statins',
            'Niacin',
            'Fenofibrate',
            'Gemfibrozil',
            'Ezetimibe',
            'Bile Acid Sequestrants',
            'Fish Oil',
            'Amlodipine',
            'Diltiazem',
            'Verapamil',
            'Nifedipine',
            'Nitroprusside',
            'Hydralazine',
            'Minoxidil',
            'Clonidine',
            'Methyldopa',
            'Alpha-Blockers',
            'Beta-Blockers',
            'ACE Inhibitors',
            'ARBs',
            'Calcium Channel Blockers',
            'Antidepressants',
            'Mood Stabilizers',
            'Antipsychotics',
            'Anticonvulsants',
            'Barbiturates',
            'Stimulants',
            'Opioids',
            'NSAIDs',
            'Muscle Relaxants',
            'Sedatives',
            'Sleep Aids',
            'Antihistamines',
            'Corticosteroids',
            'Immunosuppressants',
            'Antibiotics',
            'Antivirals',
            'Antifungals',
            'Antiparasitics',
            'Anticoagulants',
            'Platelet Aggregation Inhibitors',
            'Thrombolytics',
            'Benzodiazepines',
            'Triptans',
            'Migraine Medications',
            'Tachycardia Treatments',
            'Hypotension Treatments',
            'Cough Suppressants',
            'Decongestants',
            'Expectorants',
            'Nasal Corticosteroids',
            'Respiratory Inhalers',
            'Systemic Corticosteroids',
            'Mucolytics',
            'Antidiarrheals',
            'Proton Pump Inhibitors',
            'H2-Receptor Antagonists',
            'Laxatives',
            'Topical Treatments',
            'Dermatological Medications',
            'Vitamins and Supplements',
            'Hormonal Therapies',
            'Bioidentical Hormones',
            'Testosterone Replacement',
            'Thyroid Medications',
            'Insulins',
            'Glucose-Lowering Agents',
            'Hypoglycemic Agents',
            'Antidiabetic Medications',
            'Antigout Medications',
            'Fertility Medications',
            'Chemotherapy Agents',
            'Radiopharmaceuticals',
            'Cytotoxic Agents',
            'Antimetabolites',
            'DNA Damaging Agents',
            'Cell Cycle Specific Agents',
            'Immunomodulators',
            'Biologics',
            'Monoclonal Antibodies',
            'Biosimilars',
            'Gene Therapies',
            'Cell Therapies',
            'Stem Cell Therapies',
            'Advanced Therapies',
            'Orphan Drugs',
            'Combination Therapies',
            'Supportive Care Medications',
            'Palliative Care Medications',
            'Pain Management Medications',
            'Symptomatic Treatments',
            'Experimental Therapies',
            'Clinical Trial Medications',
            'Nutraceuticals',
            'Compounding Medications',
            'Transdermal Patches',
            'Implants',
            'Inhalers',
            'Nasal Sprays',
            'Topical Ointments',
            'Solutions',
            'Suspensions',
            'Injectables',
            'Infusions',
            'Pills',
            'Capsules',
            'Tablets',
            'Granules',
            'Powders',
            'Gelcaps',
            'Liquids',
            'Syrups',
            'Emulsions',
            'Gels',
            'Foams',
            'Creams',
            'Lotions',
            'Dressings',
            'Cleansers',
            'Antiseptics',
            'Antibacterials',
            'Antifungals',
            'Antivirals',
            'Antiparasitics',
            'Topical Steroids',
            'Biologics',
            'Oral Medications',
            'Subcutaneous Medications',
            'Intravenous Medications',
            'Intradermal Medications',
            'Intramuscular Medications',
            'Ocular Medications',
            'Otic Medications',
            'Nasal Medications',
            'Pulmonary Medications',
            'Transmucosal Medications',
            'Per rectum Medications',
            'Sublingual Medications',
            'Buccal Medications',
            'Tropical Medications',
            'Fluoride Treatments',
            'Antiarrhythmics',
            'Antihypertensives',
            'Cholesterol Medications',
            'Thyroid Medications',
            'Hormone Replacement Therapies',
            'Anti-inflammatory Medications',
            'Steroidal Medications',
            'Immunizations',
            'Vaccines',
            'Biologics',
            'Monoclonal Antibodies',
            'Biosimilars',
            'Gene Therapies',
            'Antimicrobial Agents',
            'Opioid Agonists',
            'Opioid Antagonists',
            'Opioid Receptor Modulators',
            'Cholinergic Agents',
            'Anticholinergic Agents',
            'Dopaminergic Agents',
            'Serotonergic Agents',
            'Adrenergic Agents',
            'Antihistamines',
            'Corticosteroids',
            'Beta-Blockers',
            'ACE Inhibitors',
            'ARBs',
            'Calcium Channel Blockers',
            'Antiplatelet Agents',
            'Anticoagulants',
            'Statins',
            'Fibrates',
            'Cholesterol Absorption Inhibitors',
            'Vitamin K Antagonists',
            'Thrombolytics',
            'Desmopressin',
            'Oxytocin',
            'Antidiuretics',
            'Diuretics',
            'Sodium Channel Blockers',
            'Calcium Channel Blockers',
            'Vasodilators',
            'Nitrates',
            'Renin Inhibitors',
            'Lipid-Lowering Agents',
            'Glucose-Lowering Agents',
            'Insulin Sensitizers',
            'Insulin Secretagogues',
            'Amylin Mimetics',
            'DPP-4 Inhibitors',
            'GLP-1 Agonists',
            'SGLT2 Inhibitors',
            'Thiazolidinediones',
            'Alpha-Glucosidase Inhibitors',
            'Monomeric Insulin',
            'Biosimilar Insulin',
            'Rapid-Acting Insulin',
            'Short-Acting Insulin',
            'Intermediate-Acting Insulin',
            'Long-Acting Insulin',
            'Ultra-Long-Acting Insulin',
            'Insulin Combinations',
            'Non-Insulin Diabetes Medications',
            'Thyroid Hormones',
            'Antithyroid Medications',
            'Corticosteroids',
            'Mineralocorticoids',
            'Glucocorticoids',
            'Sex Hormones',
            'Anabolic Steroids',
            'Androgens',
            'Estrogens',
            'Progestins',
            'Hormonal Contraceptives',
            'Emergency Contraceptives',
            'Fertility Medications',
            'Menopausal Hormone Therapy',
            'Testosterone Replacement Therapy',
            'Osteoporosis Medications',
            'Calcium Supplements',
            'Vitamin D Supplements',
            'Biphosphonates',
            'Parathyroid Hormone',
            'Calcitonin',
            'SERM',
            'Denosumab',
            'Antihyperuricemic Agents',
            'Glucosamine Supplements',
            'Chondroitin Supplements',
            'Fish Oil Supplements',
            'Coenzyme Q10',
            'Folic Acid',
            'Niacin',
            'Omega-3 Fatty Acids',
            'Electrolyte Supplements',
            'Mineral Supplements',
            'Vitamins',
            'Probiotics',
            'Prebiotics',
            'Digestive Enzymes',
            'Herbal Supplements',
            'Homeopathic Remedies',
            'Natural Remedies',
            'Alternative Therapies',
            'Traditional Medicine',
            'Complementary Medicine',
            'Functional Medicine',
            'Integrative Medicine',
            'Wellness Supplements',
            'Nutritional Supplements',
            'Meal Replacement Products',
            'Weight Loss Medications',
            'Appetite Suppressants',
            'Fat Blockers',
            'Carbohydrate Blockers',
            'Thermogenic Agents',
            'Diuretics for Weight Loss',
            'Fat Burners',
            'Muscle Builders',
            'Sports Supplements',
            'Energy Supplements',
            'Recovery Supplements',
            'Protein Powders',
            'Creatine',
            'Branched-Chain Amino Acids',
            'Essential Amino Acids',
            'Nitric Oxide Boosters',
            'Pre-Workout Supplements',
            'Post-Workout Supplements',
            'Testosterone Boosters',
            'Hormonal Support Supplements',
            'Zinc',
            'Magnesium',
            'Chromium',
            'Selenium',
            'Copper',
            'Manganese',
            'Iodine',
            'Boron',
            'Silica',
            'Vanadium',
            'Choline',
            'Inositol',
            'L-Carnitine',
            'L-Arginine',
            'L-Tyrosine',
            'L-Theanine',
            'Glutamine',
            'Arginine',
            'Taurine',
            'N-Acetyl Cysteine',
            'Curcumin',
            'Resveratrol',
            'Green Tea Extract',
            'Bacopa Monnieri',
            'Rhodiola Rosea',
            'Ginseng',
            'Ashwagandha',
            'Maca Root',
            'Spirulina',
            'Chlorella',
            'Beetroot Powder',
            'Aloe Vera',
            'Milk Thistle',
            'Dandelion',
            'Ginger',
            'Turmeric',
            'Peppermint',
            'Thyme',
            'Rosemary',
            'Sage',
            'Basil',
            'Parsley',
            'Cilantro',
            'Oregano',
            'Fennel',
            'Lavender',
            'Chamomile',
            'Valerian',
            'Kava',
            'St. John’s Wort',
            'Passionflower',
            'Skullcap',
            'Lemon Balm',
            'Hawthorn',
            'Ginkgo Biloba',
            'Fenugreek',
            'Nettle',
            'Cayenne Pepper',
            'Cinnamon',
            'Cloves',
            'Cardamom',
            'Black Seed',
            'Garlic',
            'Onion',
            'Horseradish',
            'Mustard Seed',
            'Chili Pepper',
            'Tamarind',
            'Cacao',
            'Honey',
            'Apple Cider Vinegar',
            'Olive Oil',
            'Coconut Oil',
            'Fish Oil',
            'Flaxseed Oil',
            'Hemp Oil',
            'Evening Primrose Oil',
            'Black Currant Oil',
            'Krill Oil',
            'Cod Liver Oil',
            'Walnut Oil',
            'Almond Oil',
            'Sesame Oil',
            'Avocado Oil',
            'Sunflower Oil',
            'Safflower Oil',
            'Canola Oil',
            'Corn Oil',
            'Peanut Oil',
            'Grapeseed Oil',
            'Macadamia Oil',
            'Pine Nut Oil',
            'Hazelnut Oil',
            'Palm Oil',
            'Tallow',
            'Lard',
            'Butter',
            'Ghee',
            'Shortening',
            'Margarine',
            'Cream Cheese',
            'Cottage Cheese',

  ];
  